package com.altran.training.weekthird.exceptionhandling;

import java.util.Scanner;

/**
 * Demo of exception being generated at runtime without handling the exception
 * Try to figure out how many exceptions can be generated by the given code.
 * 
 * @author GUR57489
 *
 */
class DivisionErrorDemo {
	public static double divide(int a, int b) {
		System.out.println("Inside divide method");
		double quotient = 0;
		quotient = a / b;//ArithmetiExcpection
		return quotient;
	}

	/**
	 * 
	 * @param args: Array of String
	 */
	public static void main(String[] args) {
		//object of Scanner class
		Scanner scanner = new Scanner(System.in);
		//reading values from user
		System.out.println("Enter first value");
		int a = scanner.nextInt();
		System.out.println("Enter second value");
		
		int b = scanner.nextInt();
		//calling divide function to get quotient as result
		System.out.println("hi");
		double ans = divide(a, b);
		System.out.println("The quotient is " + ans);
		System.out.println("hello");
		System.out.println("world");
	}
}
